### ISSUE TITLE
Feedback `PolkadotProvider`

### ISSUE THREAD

**Issue by peetzweg** [paritytech/polkadot-api#90]
Just re-watched the presentation of the `PolkadotProvider` interface and have the following feedback & questions:

As this is intended to be an unchanged interface to be used for a long time. I wonder what the official distinction between naming something `Network` and `Chain` is. If you call `Network.connect()` you get `ChainProvider` and if you `PolkadotProvider.addNetwork()` you pass ` `chainspec`. In my head this does make sense, as probably it always has been like this. However, I just want to challenge this again to make it potentially less confusing for people using this spec in the future.

https://github.com/paritytech/polkadot-api/blob/1b7b96e84cb57881c54c86dacb9b527d4fbf4829/experiments/src/PolkadotProvider.ts#L12-L22

---

As mentioned during the presentation the `Account.createTx(callData)` function receives hex encoded unsigned callData and expects `signedCallData` in return. Maybe calling it `signTx(callData)` would be a better suited name? In my head `createTx` would suggested building the actual `callData` bytes from input variables.

https://github.com/paritytech/polkadot-api/blob/1b7b96e84cb57881c54c86dacb9b527d4fbf4829/experiments/src/PolkadotProvider.ts#L6-L10

---

Regarding the `client` field in the `ChainProvider` being `GetProvider` or `SubstrateClient`. Why not let the `SubstrateClient` be a `GetProvider` compatible and give `GetProvider` a way to identify it's type, so it can be inferred that it's a `SubstrateClient`, to ease usage of the arbitrary client instance.

https://github.com/paritytech/polkadot-api/blob/1b7b96e84cb57881c54c86dacb9b527d4fbf4829/experiments/src/PolkadotProvider.ts#L6-L10

**Comment by josepot** [comment]
Hi @peetzweg ,

I appreciate you taking the time to provide this feedback. However, please know that:

1) We never stated anywhere that the `PolkadotProvider` that's currently under the `experiments` folder of this repo is the "official" one. In fact, it isn't, it really isn't... This is just an early experiment that I wrote while I was shaping up the very first versions. Our experiments folder is intentionally meant to be a bit chaotic, so nothing in it should be taken as "official".

2) You are providing public feedback while referring to private recordings, and private documents that the wider community doesn't have access to yet. 🤷 I really don't think that this is the right forum for this. On one hand because the document that I shared and that I asked for feedback for has a different API, on the other because that feedback was meant to re-shape the interface before we made it public.

So, please, your feedback is welcomed, but please add these comments on the notion document, which has the actual proposal.

> As this is intended to be an unchanged interface to be used for a long time.

Said no-one, ever.

> As this is intended to be an unchanged interface to be used for a long time. I wonder what the official distinction between naming something `Network` and `Chain` is. If you call `Network.connect()` you get `ChainProvider` and if you `PolkadotProvider.addNetwork()` you pass ` `chainspec`. In my head this does make sense, as probably it always has been like this. However, I just want to challenge this again to make it potentially less confusing for people using this spec in the future.

That's a good point. Thanks. This has been addressed in the internal doc containing the current draft. 


> Maybe calling it `signTx(callData)` would be a better suited name? In my head `createTx` would suggested building the actual `callData` bytes from input variables.

No, it wouldn't. What the function returns is the transaction, not the signed data. That's the whole point. This function takes care of all the necessary shenanigans needed to create the transaction for that particular chain. What it returns is the input of [this function](https://paritytech.github.io/json-rpc-interface-spec/api/transaction_unstable_submitAndWatch.html), the transaction.

> 
> https://github.com/paritytech/polkadot-api/blob/1b7b96e84cb57881c54c86dacb9b527d4fbf4829/experiments/src/PolkadotProvider.ts#L6-L10
> 
> Regarding the `client` field in the `ChainProvider` being `GetProvider` or `SubstrateClient`. Why not let the `SubstrateClient` be a `GetProvider` compatible and give `GetProvider` a way to identify it's type, so it can be inferred that it's a `SubstrateClient`, to ease usage of the arbitrary client instance.

Again, you are referring to an interface that it's not up-to-date. The one that I asked feedback for differers significantly from this one, and it doesn't expose the `SubstrateClient` anywhere.

To avoid confusion this experimental `PolkadotProvider` has been removed from the experiments. Please add your feedback into the correct forum 🙏 .
